import { Activity, CircleGauge, Timer, X } from "lucide-react";

export type ResourceUsage = { rss: number; heapUsed: number; heapTotal: number; heapLimit: number; external: number; codexRss: number | null; totalRss: number; uptime: number; clients: number };
export type ThreadUsage = { total: { totalTokens: number; inputTokens: number; cachedInputTokens: number; outputTokens: number; reasoningOutputTokens: number }; last: { totalTokens: number; inputTokens: number; cachedInputTokens: number; outputTokens: number; reasoningOutputTokens: number }; modelContextWindow: number | null };
export type CompactionStatus = { status: "running" | "completed"; at?: number } | null;

const bytes = (value?: number | null) => value == null ? "Unavailable" : `${(value / 1024 / 1024).toFixed(value >= 100 * 1024 * 1024 ? 0 : 1)} MB`;
const number = (value?: number | null) => value == null ? "Unavailable" : new Intl.NumberFormat(undefined, { notation: value > 999999 ? "compact" : "standard", maximumFractionDigits: 1 }).format(value);
const duration = (seconds?: number) => { const value = Math.max(0, Math.floor(seconds || 0)); const hours = Math.floor(value / 3600); const minutes = Math.floor(value % 3600 / 60); return hours ? `${hours}h ${minutes}m` : `${minutes}m`; };
const Meter = ({ value }: { value: number }) => <span className="usage-meter"><i style={{ width: `${Math.max(0, Math.min(100, value))}%` }} /></span>;

export function SettingsDrawer({ close, meta, connected, resources, account, threadUsage, active }: { close: () => void; meta: any; connected: boolean; resources: ResourceUsage | null; account: any; threadUsage: ThreadUsage | null; active: boolean }) {
  const summary = account?.usage?.summary; const limits = account?.rateLimits?.rateLimitsByLimitId?.codex || account?.rateLimits?.rateLimits;
  const rate = limits?.primary; const contextPercent = threadUsage?.modelContextWindow ? threadUsage.last.inputTokens / threadUsage.modelContextWindow * 100 : null;
  return <div className="drawer-layer settings-layer" onMouseDown={(event) => event.target === event.currentTarget && close()}><section className="settings">
    <header><div><span>Codex Web</span><b>Settings & usage</b></div><button className="icon-button" aria-label="Close settings" onClick={close}><X /></button></header>
    <div className="settings-scroll">
      <section className="settings-section"><h3><Activity />Resources <small>Live</small></h3>{resources ? <div className="resource-card"><div className="resource-total"><span><small>Total resident memory</small><b>{bytes(resources.totalRss)}</b></span><em>{resources.clients} {resources.clients === 1 ? "client" : "clients"} · {duration(resources.uptime)} uptime</em></div><div className="resource-grid"><div><small>Harness RSS</small><b>{bytes(resources.rss)}</b></div><div><small>Codex RSS</small><b>{bytes(resources.codexRss)}</b></div><div><small>Node heap</small><b>{bytes(resources.heapUsed)} / {bytes(resources.heapLimit)}</b><Meter value={resources.heapUsed / resources.heapLimit * 100} /></div><div><small>External buffers</small><b>{bytes(resources.external)}</b></div></div></div> : <div className="settings-empty">Waiting for resource metrics…</div>}</section>
      <section className="settings-section"><h3><CircleGauge />Context window</h3>{active ? threadUsage ? <div className="context-card"><div className="context-primary"><span><small>Last turn context load</small><b>{number(threadUsage.last.inputTokens)}{threadUsage.modelContextWindow ? ` / ${number(threadUsage.modelContextWindow)}` : " tokens"}</b></span>{contextPercent != null && <em>{contextPercent.toFixed(1)}%</em>}</div>{contextPercent != null && <Meter value={contextPercent} />}<div className="context-details"><span>Total thread tokens <b>{number(threadUsage.total.totalTokens)}</b></span><span>Last output <b>{number(threadUsage.last.outputTokens)}</b></span><span>Reasoning <b>{number(threadUsage.last.reasoningOutputTokens)}</b></span></div></div> : <div className="settings-empty">Token usage appears after the next model response.</div> : <div className="settings-empty">Select a session to view its context usage.</div>}</section>
      <section className="settings-section"><h3><Timer />Account usage</h3>{account?.unavailable ? <div className="settings-empty">Unavailable for the current authentication mode.</div> : summary || rate ? <div className="account-card">{rate && <div className="rate-usage"><span><small>{limits.limitName || limits.limitId || "Codex"} window</small><b>{rate.usedPercent.toFixed(0)}% used</b></span><Meter value={rate.usedPercent} /><em>{rate.resetsAt ? `Resets ${new Date(rate.resetsAt * 1000).toLocaleString()}` : `${rate.windowDurationMins || "–"} minute window`}</em></div>}<div className="account-grid"><div><small>Lifetime tokens</small><b>{number(summary?.lifetimeTokens)}</b></div><div><small>Peak daily</small><b>{number(summary?.peakDailyTokens)}</b></div><div><small>Current streak</small><b>{summary?.currentStreakDays == null ? "Unavailable" : `${summary.currentStreakDays} days`}</b></div><div><small>Longest turn</small><b>{summary?.longestRunningTurnSec == null ? "Unavailable" : duration(summary.longestRunningTurnSec)}</b></div></div></div> : <div className="settings-empty">Loading account usage…</div>}</section>
      <section className="settings-section system-details"><h3>System</h3><dl><div><dt>Workspace</dt><dd>{meta.workspace || "Not selected"}</dd></div><div><dt>Codex status</dt><dd><span className={`badge ${meta.codexStatus}`}>{meta.codexStatus}</span></dd></div><div><dt>Version</dt><dd>{meta.codexVersion}</dd></div><div><dt>Connection</dt><dd>{connected ? "WebSocket connected" : "Disconnected"}</dd></div><div><dt>Base path</dt><dd>{meta.basePath}</dd></div></dl></section>
    </div>
  </section></div>;
}
